// Generated by CoffeeScript 1.3.1
var fs, mkdirp, mkdirpSync,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

fs = require('fs');

__extends(fs, require('fs.walker'));

mkdirp = function(path, options, callback) {
  var dirname, exists, mode, parent, _ref, _ref1;
  if (options == null) {
    options = {};
  }
  _ref = require('path'), dirname = _ref.dirname, exists = _ref.exists;
  if (typeof options === 'function') {
    callback = options;
    options = {};
  }
  mode = (_ref1 = options.mode) != null ? _ref1 : 0x1ed;
  console.log('mkdirp', path);
  parent = dirname(path);
  return exists(parent, function(isExists) {
    var completion;
    completion = function(err) {
      console.log('competion', err);
      if (err != null) {
        return callback(err);
      }
      console.log('fs.mkdir', path);
      return fs.mkdir(path, mode, callback);
    };
    if (isExists) {
      return completion(null);
    } else {
      return mkdirp(parent, options, completion);
    }
  });
};

mkdirpSync = function(path, options) {
  var dirname, existsSync, mode, parent, _ref;
  if (options == null) {
    options = {};
  }
  _ref = require('path'), dirname = _ref.dirname, existsSync = _ref.existsSync;
  mode = options.mode || 0x1ed;
  parent = dirname(path);
  if (!existsSync(parent)) {
    mkdirpSync(parent, options);
  }
  if (!existsSync(path)) {
    return fs.mkdirSync(path, mode);
  }
};

fs.mkdirp = mkdirp;

fs.mkdirpSync = mkdirpSync;

module.exports = fs;
